name: cashier_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cutadapt
  - starcode
  - fastx_toolkit
  - pear
  - pysam
  - rich
  - pip
  - pip:
    - git+https://github.com/DaylinMorgan/pycashier/
