name: cashierenv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - cutadapt>=3.5
  - starcode>=1.4
  - pysam=0.17*
  - fastp=0.23*
  - rich=10.12*
  - rich-click=1.2*
  - ruamel.yaml=0.17*
  - pycashier
