[project]
name = "pycashier"
authors = ["Daylin Morgan <daylinmorgan@gmail.com>"]
channels = ["conda-forge" , "bioconda"]
platforms = ["linux-64"]

[tasks]

[environments]
dev = ["base", "bioconda", "dev", "build"]
prod = ["base","bioconda", "prod"]
build = ["build"]
test = ["bioconda", "dev", "test"]
test38 = ["bioconda", "dev", "test", "test38"]
test39 = ["bioconda", "dev", "test", "test39"]
test310 = ["bioconda", "dev", "test", "test310"]

[host-dependencies]
pip = "*"

[feature.base.dependencies]
# https://bioconda.github.io/faqs.html#what-versions-are-supported
python = ">=3.8,<3.11"

[feature.dev.dependencies]
pdm = ">=2.12.4,<2.13"

[feature.prod.dependencies]
tomlkit = ">=0.12.4,<0.13"
rich = ">=13.7.1,<13.8"
click-rich-help = ">=22.1.1,<22.2"
click = ">=8.1.7,<8.2"
polars = ">=0.20.13,<0.21"

[feature.bioconda.dependencies]
cutadapt = ">=4.6,<5"
starcode = ">=1.4,<2"
fastp = ">=0.23.4,<0.24"
pysam = ">=0.22.0,<0.23"


[feature.test.dependencies]
pytest = ">=7.2.0"
pytest-cov= ">=4.1.0"

[feature.test38.dependencies]
python = "3.8.*"
[feature.test39.dependencies]
python = "3.9.*"
[feature.test310.dependencies]
python = "3.10.*"

[feature.build.dependencies]
build = "*"
pdm-backend = "*"
git = "*" # for scm-versioning with pdm

[feature.dev.tasks]
postinstall = "pdm install"

[feature.build.tasks]
build-wheel = "python -m build --no-isolation --wheel ."

[feature.prod.tasks]
postinstall-production = "pip install --no-deps --disable-pip-version-check dist/pycashier-*.whl"
