channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.10
  - cutadapt>=4.1
  - starcode>=1.4
  - pysam>=0.22
  - fastp>=0.23
  - rich>=10
  - click-rich-help>=22.1
  - click>=8.1.0
  - tomlkit>=0.10
  - polars>=0.20
